export const stages=["New","Intro requested","In conversation","Meeting scheduled","Evaluating","Closed"] as const;
export type Stage=typeof stages[number];
export type MailMessage={id:string;from:string;to:string;subject:string;body:string;at:string;direction:"inbound"|"outbound"};
export type MeetingNote={id:string;date:string;body:string;topics:string[];askedForReferrals:boolean};
export type ResearchSource={title:string;url:string;publishedAt?:string;evidence:string};
export type PublicProfile={role:string;profile?:string;kind?:Contact['kind'];summary:string;interests:string[];networkAngles:string[];sources:ResearchSource[];checkedAt:string};
export type ResearchedPerson={id:string;companyId:string;name:string;role:string;kind:Contact['kind'];profile?:string;interests:string[];summary:string;networkAngles:string[];sources:ResearchSource[];checkedAt:string};
export type NetworkResearch={schemaVersion:1;generatedAt:string;people:ResearchedPerson[];movements:Movement[]};
export type Deal={id:string;companyId:string;name:string;startup:string;link:string;reason:string;referrer:string;referrerEmail:string;category:string;stage:Stage;owner:string;permission:"Yes"|"Ask first";followUp:string;notes:string;messages:MailMessage[];updatedAt:string;unread:boolean;source:"email"|"manual"|"sample";providerThreadId?:string;referrerPersonId?:string;intake?:"Known to referrer"|"Passed to Together"};
export type Contact={id:string;companyId:string;name:string;email:string;role:string;interests:string;kind?:"Founder"|"Leadership"|"Team"|"Alumni";profile?:string;sourceUrl?:string;notes?:string;lastContactAt?:string;nextFollowUpAt?:string;fundSentiment?:"Positive"|"Mixed"|"Negative"|"Unknown";relationshipStrength?:"Strong"|"Developing"|"Weak"|"Unknown";referralAwareness?:"Clear"|"Needs reminder"|"Unknown";referralUnderstanding?:"Clear"|"Needs context"|"Unknown";dealFlow?:"Frequent"|"Occasional"|"Unknown";referralAskAt?:string;relationshipOwner?:string;networkDbUrl?:string;meetingNotes?:MeetingNote[];research?:PublicProfile};
export type MailDraft={id:string;companyId:string;to:string;subject:string;body:string;status:"Draft"|"Saved to Gmail";providerId?:string;providerRevision?:string;createdAt:string;dealId?:string;personId?:string;archivedAt?:string;resourceId?:string;opportunityId?:string;purpose?:'content'|'referral-ask'|'referral-reply'};
export type Settings={enabled:boolean;frequencyDays:2|7;mailbox:string;emailQuery:string;lastMailSync?:string;lastResearchAt?:string;schedulerRegistered:boolean;focusCompanyIds?:string[]};
export type MonitorResult={companyId:string;status:"Baseline saved"|"Content changed"|"No change"|"Failed";url:string;summary:string;before:string;checkedAt:string};
export type MonitorReport={id:string;startedAt:string;completedAt:string;status:"Running"|"Completed"|"Partial";results:MonitorResult[];nextIndex:number;trigger:"Scheduled"|"Manual";peopleStatus:string};
export type Movement={id:string;companyId:string;person:string;profile:string;previousRole:string;currentRole:string;previousCompany:string;currentCompany:string;type:"Departure"|"New role"|"Started company";observedAt:string;sourceUrl:string;provider:"Clay"|"Harmonic"|"Public source";evidence:string;confirmed:boolean;personId?:string;eventDate?:string;historical?:boolean};
export type ContentSource={title:string;url:string;publishedAt?:string};
export type RecipientAngle={companyId:string;personName:string;whyThisPerson:string;angle:string;emailSubject:string;emailBody:string};
export const contentKinds=['Research breakthrough','Industry research','Buyer data'] as const;
export type ContentKind=typeof contentKinds[number];
export type FeedItem={id:string;title:string;publisher:string;url:string;publishedAt:string;companyIds:string[];topic:string;summary:string;whyRelevant:string;emailSubject:string;emailBody:string;checkedAt:string;format?:'Research'|'Article'|'Podcast'|'Newsletter'|'Guide';kind?:ContentKind;engagementMove?:string;takeaways?:string[];discussionQuestion?:string;recipientAngles?:RecipientAngle[];sources?:ContentSource[]};
export type ReferralOpportunity={id:string;companyId:string;referrerPersonName:string;candidateName:string;startup:string;website:string;sector:string;connectionType:string;connectionEvidence:string;whyRelevant:string;suggestedAsk:string;sources:ContentSource[];checkedAt:string;eventDate?:string;limitations:string;evidenceStrength?:string;fitPriority?:string;illustrative?:boolean;matchBasis?:string};
export type Notice={id:string;title:string;detail:string;reportId:string;read:boolean;createdAt:string};
export type Connections={gmail:boolean;gmailConfigured:boolean;people:boolean;peopleProvider:string;scheduler:boolean;mailbox:string};
export type PlatformData={deals:Deal[];contacts:Contact[];drafts:MailDraft[];reports:MonitorReport[];movements:Movement[];feed:FeedItem[];opportunities?:ReferralOpportunity[];notices:Notice[];settings:Settings;connections:Connections};
export const defaultSettings:Settings={enabled:true,frequencyDays:2,mailbox:"shivam@together.fund",emailQuery:"label:Together-Referrals",schedulerRegistered:false};
// Anchor report due dates to 10:00 Asia/Kolkata, avoiding daily-run time jitter.
export function nextReportDue(previous:string,days:number){const localDay=Math.floor((Date.parse(previous)+330*60000)/86400000);return (localDay+days)*86400000+270*60000}
