import {useState} from 'react';
import {ArrowRight, ArrowUpRight, Users, Radio, MessageSquare, Inbox, Play, Plus, Mail, ExternalLink, Check, CalendarDays} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {toast} from 'sonner';
import {companies} from './data';
import {content} from './engagement-content';
import type {Contact,Movement,PlatformData} from './platform-types';
import './sourcing-flow.css';

const companyName=(id:string)=>companies.find(c=>c.id===id)?.name||'Portfolio company';
const date=(s?:string)=>s?new Date(s.length===10?s+'T12:00:00':s).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'}):'Not recorded';
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
function Choice({value,onChange,label,items}:{value:string;onChange:(v:string)=>void;label:string;items:{id:string;name:string}[]}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue placeholder="Choose a person"/></SelectTrigger><SelectContent>{items.map(i=><SelectItem key={i.id} value={i.id}>{i.name}</SelectItem>)}</SelectContent></Select>}

export function SourcingStory({view,onNavigate,onExample}:{view:string;onNavigate:(v:string)=>void;onExample:()=>void}){
 const [open,setOpen]=useState(false),[step,setStep]=useState(0);
 const steps=[{id:'people',title:'Map your people',sub:'Founders, key team & alumni',icon:Users},{id:'monitor',title:'Follow their moves',sub:'Departures, new roles & startups',icon:Radio},{id:'engage',title:'Stay in touch',sub:'Useful content & thoughtful asks',icon:MessageSquare}];
 const example=[
  {title:'Start with a relationship',tag:'01 · PEOPLE MAP',body:'A portfolio founder knows Riya, a former teammate. The relationship is mapped to the portfolio company, alongside other founders and key team members.',detail:'Company → portfolio founder → former teammate',action:'What changes next?'},
  {title:'Notice the next chapter',tag:'02 · TALENT MOVEMENT',body:'A public announcement says Riya is building TeamLens. Review the source and the role change before treating it as a startup signal.',detail:'Previous role → founder at TeamLens → source reviewed',action:'How do we engage?'},
  {title:'Be useful, then make a specific ask',tag:'03 · RELATIONSHIP',body:'Share a relevant customer-discovery resource with the portfolio founder. Ask whether Riya would welcome a conversation with Together. Record the reply and the next follow-up.',detail:'“Would an introduction be useful to her? Happy to share a short note.”',action:'Where does the referral go?'},
  {title:'Follow through on the introduction',tag:'OUTCOME · REFERRAL',body:'Riya / TeamLens appears in the referral inbox, linked to the portfolio company. The owner, permission and conversation stage make the next step clear.',detail:'New → ask permission → introduction → conversation',action:'Open sample referral'}
 ];
 return <><div className="story-topline"><span>PORTFOLIO RELATIONSHIPS → FOUNDER CONVERSATIONS</span><button className="p-link" onClick={()=>{setStep(0);setOpen(true)}}><Play size={13}/>Walk through an example</button></div><nav className="sourcing-story" aria-label="Sourcing workflow">{steps.map((s,i)=><button key={s.id} className={view===s.id?'active':''} aria-current={view===s.id?'step':undefined} onClick={()=>onNavigate(s.id)}><span className="story-number">0{i+1}</span><span><strong>{s.title}</strong><small>{s.sub}</small></span><ArrowRight className="story-arrow" size={16}/></button>)}<button className={`story-outcome ${view==='referrals'?'active':''}`} onClick={()=>onNavigate('referrals')} aria-current={view==='referrals'?'step':undefined}><Inbox size={19}/><span><strong>Referral inbox</strong><small>Take the conversation forward</small></span></button></nav>
 <Dialog open={open} onOpenChange={setOpen}><DialogContent className="story-dialog"><DialogHeader><DialogTitle>How portfolio sourcing works</DialogTitle><DialogDescription>Illustrative walkthrough. Riya, TeamLens and these interactions are fictional; nothing here is a detected move or a sent message.</DialogDescription></DialogHeader><div className="example-progress">{example.map((s,i)=><button key={s.tag} aria-label={`Example step ${i+1}: ${s.title}`} aria-current={i===step?'step':undefined} className={i===step?'active':''} onClick={()=>setStep(i)}>{i+1}</button>)}</div><div className="example-body"><p className="overline">{example[step].tag}</p><h2>{example[step].title}</h2><p>{example[step].body}</p><blockquote>{example[step].detail}</blockquote></div><div className="example-actions"><span>Step {step+1} of 4</span><button className="p-primary" onClick={()=>{if(step<3)setStep(step+1);else{setOpen(false);onExample()}}}>{example[step].action}<ArrowRight size={15}/></button></div></DialogContent></Dialog></>;
}

export function TalentMoves({data,person,onPerson,onEngage,onSave,onConnections}:{data:PlatformData;person?:Contact;onPerson:(id:string)=>void;onEngage:(p:Contact,movement?:Movement)=>void;onSave:(kind:string,value:unknown)=>Promise<void>;onConnections:()=>void}){
 const [filter,setFilter]=useState('all'),[editing,setEditing]=useState<Movement|null>(null),[open,setOpen]=useState(false),[saving,setSaving]=useState(false),[personId,setPersonId]=useState('');
 const moves=data.movements.filter(m=>(filter==='all'||m.type===filter)&&(!person||(m.personId===person.id||m.companyId===person.companyId&&m.person===person.name)));
 function edit(m?:Movement){setEditing(m||null);setPersonId(m?.personId||data.contacts.find(p=>p.name===m?.person&&p.companyId===m?.companyId)?.id||person?.id||data.contacts[0]?.id||'');setOpen(true)}
 return <><div className="page-title"><div><p className="overline">02 · FOLLOW THEIR MOVES</p><h1>Know when their next chapter starts.</h1><p>Review what changed. Keep the relationship warm. Explore a startup only when there is evidence.</p></div><button className="p-primary" onClick={()=>edit()} disabled={!data.contacts.length}><Plus size={16}/>Record a move</button></div>
 <div className="people-feed-status"><span className="status-icon"><Radio size={20}/></span><div><strong>{data.connections.people?'People feed connected':'Automatic people tracking needs a data connection'}</strong><p>{data.connections.people?`Observations from ${data.connections.peopleProvider}. Review sources before reaching out.`:'Your mapped people are the watchlist. Clay / Harmonic is not connected yet; sourced observations can be recorded below.'}</p></div><button className="p-secondary" onClick={onConnections}>Connection details<ArrowUpRight size={14}/></button></div>
 <div className="moves-toolbar"><div className="segmented" aria-label="Movement type">{['all','Departure','New role','Started company'].map(t=><button key={t} aria-pressed={filter===t} className={filter===t?'active':''} onClick={()=>setFilter(t)}>{t==='all'?'All moves':t==='Started company'?'Started a company':t==='New role'?'New roles':'Departures'}</button>)}</div>{person&&<button className="person-context" onClick={()=>onPerson('')}>{person.name} <span>× Clear person</span></button>}</div>
 {moves.length?<div className="talent-moves">{moves.map(m=>{const p=data.contacts.find(p=>p.id===m.personId)||data.contacts.find(p=>p.companyId===m.companyId&&p.name===m.person);return <article className="move-card" key={m.id}><div className="section-heading"><div><p className="overline">{companyName(m.companyId)} · {m.type}</p><h2>{m.person}</h2></div><span className={`p-badge ${m.confirmed?'green':'amber'}`}>{m.confirmed?'Evidence reviewed':'Needs review'}</span></div><div className="move-journey"><div><small>PREVIOUSLY</small><strong>{m.previousRole||'Role not recorded'}</strong><span>{m.previousCompany}</span></div><ArrowRight size={20}/><div><small>OBSERVED</small><strong>{m.currentRole||'Next role unknown'}</strong><span>{m.currentCompany||'Destination not announced'}</span></div></div><p>{m.evidence}</p><div className="move-footer"><span>{date(m.observedAt)} · {m.provider}</span><a href={m.sourceUrl} className="p-link" target="_blank" rel="noreferrer">Review source <ExternalLink size={13}/></a><button className="p-link" onClick={()=>edit(m)}>Edit observation</button>{p&&<button className="p-secondary" onClick={()=>onEngage(p,m)}><MessageSquare size={14}/>Prepare a check-in</button>}</div></article>})}</div>:<div className="moves-empty"><div className="moves-illustration"><span><Users size={23}/></span><ArrowRight size={20}/><span><Radio size={23}/></span><ArrowRight size={20}/><span><MessageSquare size={23}/></span></div><h2>{filter==='all'?'No sourced moves recorded here yet':'No matching moves'}</h2><p>A departure, a new role, or a startup launch appears here with the person, the source and a next action. A job change alone does not mean someone is starting a company.</p><button className="p-link" onClick={()=>edit()}>Add an observation you can verify <Plus size={14}/></button></div>}
 <Dialog open={open} onOpenChange={setOpen}><DialogContent className="platform-dialog"><DialogHeader><DialogTitle>{editing?'Review a movement':'Record a sourced movement'}</DialogTitle><DialogDescription>Attach public evidence to a mapped person. This is a manual observation, not an automated scan.</DialogDescription></DialogHeader><form key={editing?.id||'new'} onSubmit={async e=>{e.preventDefault();if(saving)return;const f=new FormData(e.currentTarget),p=data.contacts.find(p=>p.id===personId);if(!p)return;setSaving(true);try{await onSave('movement',{id:editing?.id||`movement-${crypto.randomUUID()}`,personId:p.id,companyId:p.companyId,person:p.name,profile:p.profile||'',previousRole:String(f.get('previousRole')),previousCompany:String(f.get('previousCompany')),currentRole:String(f.get('currentRole')),currentCompany:String(f.get('currentCompany')),type:String(f.get('type')),observedAt:String(f.get('observedAt')),sourceUrl:String(f.get('sourceUrl')),provider:editing?.provider||'Public source',evidence:String(f.get('evidence')),confirmed:f.get('confirmed')==='on'});setOpen(false);toast.success('Movement saved with its source')}catch(e){toast.error(e instanceof Error?e.message:'Could not save movement')}finally{setSaving(false)}}}>
 <label>Mapped person<Choice label="Movement person" value={personId} onChange={setPersonId} items={data.contacts.map(p=>({id:p.id,name:`${p.name} · ${companyName(p.companyId)}`}))}/></label><div className="form-row"><label>Type of change<select name="type" defaultValue={editing?.type||'New role'}><option>Departure</option><option>New role</option><option>Started company</option></select></label><label>Observed on<input name="observedAt" type="date" required max={today()} defaultValue={editing?.observedAt.slice(0,10)||today()}/></label></div><div className="form-row"><label>Previous role<input name="previousRole" defaultValue={editing?.previousRole||person?.role||''}/></label><label>Previous company<input name="previousCompany" required defaultValue={editing?.previousCompany||companyName(data.contacts.find(p=>p.id===personId)?.companyId||'')}/></label></div><div className="form-row"><label>New role<input name="currentRole" defaultValue={editing?.currentRole}/></label><label>New company / project<input name="currentCompany" defaultValue={editing?.currentCompany}/></label></div><label>Public evidence URL<input name="sourceUrl" type="url" required pattern="https?://.*" defaultValue={editing?.sourceUrl} placeholder="https://…"/></label><label>What does the source establish?<textarea name="evidence" required rows={3} defaultValue={editing?.evidence} placeholder="Quote or summarize the dated role / company announcement."/></label><label className="check-label"><input type="checkbox" name="confirmed" defaultChecked={editing?.confirmed}/>I reviewed the source and it supports this change</label><button className="p-primary" disabled={saving}>{saving?'Saving…':'Save observation'}</button></form></DialogContent></Dialog></>;
}

export function RelationshipDesk({data,person,onPerson,onCompose,onSave,onReferral,initialIntent='useful',movementId}:{movementId?:string;initialIntent?:string;data:PlatformData;person?:Contact;onPerson:(id:string)=>void;onCompose:(p:Contact,subject:string,body:string)=>void;onSave:(kind:string,value:unknown)=>Promise<void>;onReferral:(p:Contact)=>void}){
 const [intent,setIntent]=useState(initialIntent),[logging,setLogging]=useState(false),[saving,setSaving]=useState(false);
 const p=person||data.contacts[0];
 if(!p)return <div className="p-panel p-empty"><h2>Add a person to start a relationship</h2><p>Map founders, key team members or alumni first.</p></div>;
 const first=p.name.split(' ')[0];
 const personMoves=data.movements.filter(m=>m.personId===p.id||m.companyId===p.companyId&&m.person===p.name);
 const move=personMoves.find(m=>m.id===movementId)||personMoves.filter(m=>m.confirmed).sort((a,b)=>b.observedAt.localeCompare(a.observedAt))[0];
 const intentions=[{id:'useful',title:'Share something useful',text:'Research, a product insight or help with a current priority.'},{id:'checkin',title:'Keep the relationship warm',text:'Catch up, offer help and learn what they are working on.'},{id:'referral',title:'Ask who we should meet',text:'Builders they mentor, former teammates or products they rate.'}];
 return <section className="relationship-desk"><div className="relationship-target"><div><span className="overline">START WITH A PERSON</span><Choice label="Engagement person" value={p.id} onChange={onPerson} items={data.contacts.map(c=>({id:c.id,name:`${c.name} · ${companyName(c.companyId)}`}))}/></div><div className="relationship-facts"><span>Last conversation<strong>{date(p.lastContactAt)}</strong></span><span>Next follow-up<strong>{date(p.nextFollowUpAt)}</strong></span><button className="p-link" onClick={()=>setLogging(true)}><CalendarDays size={14}/>Log a touchpoint</button></div></div>
 <div className="engagement-intents">{intentions.map(i=><button key={i.id} className={intent===i.id?'active':''} aria-pressed={intent===i.id} onClick={()=>setIntent(i.id)}><strong>{i.title}</strong><span>{i.text}</span></button>)}</div>
 <div className="intent-detail">{intent==='useful'?<><div><span className="p-badge">GIVE VALUE FIRST</span><h3>A reason to reach out to {first}</h3><p>{p.interests?`Their recorded priorities: ${p.interests}`:`Choose a relevant resource for ${companyName(p.companyId)} below, then add your own perspective.`}</p><p className="p-note">A useful note can stand on its own. It does not need a referral ask.</p></div><a className="p-secondary" href="#matched-research">Choose a resource <ArrowRight size={14}/></a></>:intent==='checkin'?<><div><span className="p-badge">RELATIONSHIP BEFORE REFERRALS</span><h3>{move?.confirmed?'A reviewed move is a reason to reconnect':'Make space for their next chapter'}</h3><p>{move?.confirmed?`${p.name}: ${move.evidence}`:'Ask about their priorities and offer help. Only reference a role change when you have reviewed evidence.'}</p></div><button className="p-primary" onClick={()=>onCompose(p,`Catching up, ${first}`,`Hi ${first},\n\n${move?.confirmed?`I saw the update about ${move.currentCompany||'your next chapter'}. I would love to hear more when you are ready.\n\n`:''}What are you spending most of your time on right now? If there is a problem we can help with — a customer introduction, a hire, or someone to compare notes with — I would be happy to help.\n\nShivam`)}><Mail size={14}/>Draft a check-in</button></>:<><div><span className="p-badge">ONE SPECIFIC ASK</span><h3>Which part of {first}’s network is relevant?</h3><p>Choose a reason below. Ask for an introduction only if the builder wants one.</p><div className="ask-buttons">{content.slice(0,3).map((t,i)=><button className="p-secondary" key={t.id} onClick={()=>onCompose(p,t.title,t.message.replaceAll('NAME',first))}>{['People they mentor','Former teammates','Products they are pitched'][i]}<ArrowUpRight size={13}/></button>)}</div></div></>}</div>
 <div className="relationship-outcome"><span><MessageSquare size={16}/>When the conversation leads to a name, keep the context attached.</span><button className="p-link" onClick={()=>onReferral(p)}>Add a referral from {first}<ArrowRight size={14}/></button></div>
 <Dialog open={logging} onOpenChange={setLogging}><DialogContent className="platform-dialog"><DialogHeader><DialogTitle>Log a conversation with {first}</DialogTitle><DialogDescription>Record a real exchange. Saving an email draft does not count as contacting someone.</DialogDescription></DialogHeader><form key={p.id} onSubmit={async e=>{e.preventDefault();if(saving)return;const f=new FormData(e.currentTarget);setSaving(true);try{await onSave('contact',{...p,lastContactAt:String(f.get('lastContactAt')),nextFollowUpAt:String(f.get('nextFollowUpAt')),notes:String(f.get('notes'))});setLogging(false);toast.success('Relationship updated')}catch(e){toast.error(e instanceof Error?e.message:'Could not save conversation')}finally{setSaving(false)}}}><div className="form-row"><label>Conversation date<input type="date" name="lastContactAt" required max={today()} defaultValue={today()}/></label><label>Next follow-up<input type="date" name="nextFollowUpAt" defaultValue={p.nextFollowUpAt}/></label></div><label>Relationship notes<textarea name="notes" rows={5} defaultValue={p.notes} placeholder="What did you discuss? How can we help? What should happen next?"/></label><button className="p-primary" disabled={saving}><Check size={14}/>Save touchpoint</button></form></DialogContent></Dialog>
 </section>;
}
